# docker-compose.yml
version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: khumoyun21
      POSTGRES_PASSWORD: khumoyun21
      POSTGRES_DB: schoolio
    ports:
      - "5432:5432" # Exposes the database on your localhost
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data even if the container restarts
  app:
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_PRISMA_URL: postgresql://khumoyun21:khumoyun21@localhost:5432/schoolio
    depends_on:
      - postgres
volumes:
  postgres_data:
